name: "creative"
services:
  app:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8090"
    volumes:
      - .:/backend
    expose:
      - "8090"
    ports:
      - "8090:8090"
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: creative
      POSTGRES_USER: creative_user
      POSTGRES_PASSWORD: Isc@Creat!ve
    volumes:
      - db:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5432:5432"
volumes:
  backend:
    driver: local
  db:
    driver: local
