# Generated by Django 4.1.7 on 2023-03-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesscard', '0002_alter_businessrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessrequest',
            name='full_name_ar',
            field=models.CharField(default='', max_length=250, verbose_name='Full Name Ar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessrequest',
            name='full_name_en',
            field=models.CharField(default='', max_length=250, verbose_name='Full Name En'),
            preserve_default=False,
        ),
    ]
