# Generated by Django 4.1.7 on 2023-03-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesscard', '0003_businessrequest_full_name_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessrequest',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Approved', 'Approved'), ('Reject', 'Reject'), ('In Printing', 'In Printing'), ('Done', 'Done')], default='Draft', max_length=250, verbose_name='Status'),
        ),
    ]
