# Generated by Django 4.1.7 on 2023-03-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesscard', '0004_businessrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Reject', 'Reject'), ('In Printing', 'In Printing'), ('Done', 'Done')], default='Pending', max_length=250, verbose_name='Status'),
        ),
    ]
