# Generated by Django 4.1.7 on 2023-03-30 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('businesscard', '0005_alter_businessrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessrequest',
            name='status_change_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Status Change By'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessrequest',
            name='status_change_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_status_change_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
