# Generated by Django 4.1.7 on 2023-03-30 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('businesscard', '0007_alter_businessrequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessrequest',
            name='status_change_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Status Change By'),
        ),
        migrations.AlterField(
            model_name='businessrequest',
            name='status_change_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_status_change_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
