# Generated by Django 4.1.7 on 2023-03-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesscard', '0008_alter_businessrequest_status_change_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZohoToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=250, verbose_name='Value')),
            ],
        ),
    ]
