# Generated by Django 4.1.7 on 2024-07-11 07:15

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import guideline.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=250, verbose_name='Title')),
                ('IsActive', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ColourPalette',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=250, verbose_name='Title')),
                ('Description', ckeditor.fields.RichTextField(default='', verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GraphicStyle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=250, verbose_name='Title')),
                ('Description', ckeditor.fields.RichTextField(default='', verbose_name='Description')),
                ('Image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='logo_images', verbose_name='Image')),
                ('Usage', ckeditor.fields.RichTextField(default='', verbose_name='Usage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageList',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='logo_images', verbose_name='Image')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('Code', models.CharField(max_length=10, unique=True)),
                ('Name', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Texts',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Text', ckeditor.fields.RichTextField(default='', verbose_name='text')),
                ('IsActive', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Typography',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=250, verbose_name='Title')),
                ('Description', ckeditor.fields.RichTextField(default='', verbose_name='Description')),
                ('TypeWeights', ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Type Weights')),
                ('KerningTracking', ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Kerning & Tracking')),
                ('Leading', ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Leading')),
                ('TypeColour', ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Type Colour')),
                ('ImproperUse', ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Improper Use')),
                ('Language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guideline.language')),
                ('Texts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guideline.texts', verbose_name='Texts')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToneOfVoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Description', ckeditor.fields.RichTextField(default='', verbose_name='Description')),
                ('IsActive', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photography',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=250, verbose_name='Title')),
                ('Description', ckeditor.fields.RichTextField(default='', verbose_name='Description')),
                ('IsActive', models.BooleanField(default=False)),
                ('Images', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guideline.imagelist', verbose_name='Images')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LogoSection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=250, verbose_name='Title')),
                ('Description', ckeditor.fields.RichTextField(default='', verbose_name='Description')),
                ('Image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='logo_images', verbose_name='Image')),
                ('IsActive', models.BooleanField(default=False)),
                ('Images', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guideline.imagelist', verbose_name='ImageList')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Description', ckeditor.fields.RichTextField(default='', verbose_name='Description')),
                ('Image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='logo_images', verbose_name='Image')),
                ('Sections', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guideline.logosection', verbose_name='ImageList')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Guidelines',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Introduction', models.CharField(max_length=250, verbose_name='Introduction')),
                ('Application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guideline.application', verbose_name='Applications')),
                ('ColourPalette', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guideline.colourpalette', verbose_name='Colour Palette')),
                ('GraphicStyle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guideline.graphicstyle', verbose_name='Graphic Style')),
                ('Logos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guideline.logo', verbose_name='Logos')),
                ('Photography', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guideline.photography', verbose_name='Photo graphy')),
                ('ToneOfVoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guideline.toneofvoice', verbose_name='Tone Of Voice')),
                ('Typography', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guideline.typography', verbose_name='Typography')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='graphicstyle',
            name='Images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guideline.imagelist', verbose_name='Image List'),
        ),
        migrations.AddField(
            model_name='graphicstyle',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='graphicstyle',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.CreateModel(
            name='ColourPaletteSection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=250, verbose_name='Title')),
                ('PMS', guideline.models.PMSField(blank=True, max_length=10, null=True, verbose_name='PMS')),
                ('CMYK', guideline.models.CMYKField(blank=True, max_length=15, null=True, verbose_name='CMYK')),
                ('RGB', guideline.models.RGBField(blank=True, max_length=11, null=True, verbose_name='RGB')),
                ('HEX', guideline.models.HEXField(blank=True, max_length=7, null=True, verbose_name='HEX')),
                ('IsActive', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='colourpalette',
            name='Sections',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guideline.logosection', verbose_name='ImageList'),
        ),
        migrations.AddField(
            model_name='colourpalette',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='colourpalette',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AddField(
            model_name='application',
            name='Images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guideline.imagelist', verbose_name='Images'),
        ),
        migrations.AddField(
            model_name='application',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='application',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
    ]
