# Generated by Django 4.1.7 on 2024-07-11 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guideline', '0002_remove_guidelines_application_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logo',
            name='Sections',
        ),
        migrations.AddField(
            model_name='logosection',
            name='Logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guideline.logo', verbose_name='LogoSection'),
        ),
    ]
