# Generated by Django 4.1.7 on 2024-07-11 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guideline', '0003_remove_logo_sections_logosection_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colourpalette',
            name='Sections',
        ),
        migrations.AddField(
            model_name='colourpalettesection',
            name='ColourPalette',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guideline.colourpalette', verbose_name='ColourPalette'),
        ),
    ]
