# Generated by Django 4.1.7 on 2024-07-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guideline', '0004_remove_colourpalette_sections_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='guidelines',
        ),
        migrations.RemoveField(
            model_name='colourpalette',
            name='guidelines',
        ),
        migrations.RemoveField(
            model_name='colourpalettesection',
            name='ColourPalette',
        ),
        migrations.RemoveField(
            model_name='graphicstyle',
            name='guidelines',
        ),
        migrations.RemoveField(
            model_name='logo',
            name='guidelines',
        ),
        migrations.RemoveField(
            model_name='photography',
            name='guidelines',
        ),
        migrations.RemoveField(
            model_name='toneofvoice',
            name='guidelines',
        ),
        migrations.RemoveField(
            model_name='typography',
            name='guidelines',
        ),
        migrations.AddField(
            model_name='guidelines',
            name='Application',
            field=models.ManyToManyField(blank=True, to='guideline.application', verbose_name='Applications'),
        ),
        migrations.AddField(
            model_name='guidelines',
            name='ColourPalette',
            field=models.ManyToManyField(blank=True, to='guideline.colourpalette', verbose_name='Colour Palette'),
        ),
        migrations.AddField(
            model_name='guidelines',
            name='GraphicStyle',
            field=models.ManyToManyField(blank=True, to='guideline.graphicstyle', verbose_name='Graphic Style'),
        ),
        migrations.AddField(
            model_name='guidelines',
            name='Logo',
            field=models.ManyToManyField(blank=True, to='guideline.logo', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='guidelines',
            name='Photography',
            field=models.ManyToManyField(blank=True, to='guideline.photography', verbose_name='Photography'),
        ),
        migrations.AddField(
            model_name='guidelines',
            name='ToneOfVoice',
            field=models.ManyToManyField(blank=True, to='guideline.toneofvoice', verbose_name='Tone Of Voice'),
        ),
        migrations.AddField(
            model_name='guidelines',
            name='Typography',
            field=models.ManyToManyField(blank=True, to='guideline.typography', verbose_name='Typography'),
        ),
    ]
