# Generated by Django 4.1.7 on 2024-07-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guideline', '0006_alter_guidelines_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='Title',
            field=models.CharField(default='', max_length=250, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
