# Generated by Django 4.1.7 on 2024-07-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guideline', '0007_logo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='colourpalette',
            name='Colors',
            field=models.ManyToManyField(blank=True, to='guideline.colourpalettesection', verbose_name='Typography'),
        ),
    ]
