# Generated by Django 4.1.7 on 2024-07-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guideline', '0009_alter_colourpalette_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='typography',
            name='Bold',
            field=models.CharField(default='', max_length=250, verbose_name='Bold'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typography',
            name='Regular',
            field=models.CharField(default='', max_length=250, verbose_name='Regular'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typography',
            name='Typeface',
            field=models.CharField(default='', max_length=250, verbose_name='Typeface'),
            preserve_default=False,
        ),
    ]
