# Generated by Django 4.1.7 on 2024-07-22 11:33

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('guideline', '0011_alter_typography_bold_alter_typography_regular'),
    ]

    operations = [
        migrations.AddField(
            model_name='typography',
            name='ImproperUseImage',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='logo_images', verbose_name='Improper Use Image'),
        ),
    ]
