# Generated by Django 4.1.7 on 2024-07-22 12:13

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('guideline', '0012_typography_improperuseimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typography',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='graphicstyle',
            name='Image',
        ),
        migrations.AddField(
            model_name='graphicstyle',
            name='Logo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='logo_images', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='graphicstyle',
            name='Images',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='logo_images', verbose_name='Images'),
        ),
    ]
