# Generated by Django 4.1.7 on 2024-07-22 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guideline', '0013_alter_typography_options_remove_graphicstyle_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphicstyle',
            name='Usage',
        ),
    ]
