# Generated by Django 4.1.7 on 2024-07-23 06:40

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('guideline', '0014_remove_graphicstyle_usage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graphicstyle',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='photography',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='toneofvoice',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='photography',
            name='Images',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='logo_images', verbose_name='Images'),
        ),
    ]
