# Generated by Django 4.1.7 on 2024-07-23 06:44

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('guideline', '0015_alter_graphicstyle_options_alter_photography_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='application',
            name='Images',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='logo_images', verbose_name='Images'),
        ),
    ]
